/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as AdminTelegramRouteImport } from './routes/admin/telegram'
import { Route as ApiDownloadIdRouteImport } from './routes/api/download/$id'
import { Route as ApiPublicGuideYoutubeDotpyRouteImport } from './routes/api/public/guide/youtube[.]py'
import { Route as ApiPublicTelegramSetupRouteImport } from './routes/api/public/telegram/setup'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicV1DownloadRouteImport } from './routes/api/public/v1/download'
import { Route as ApiPublicV1SearchRouteImport } from './routes/api/public/v1/search'
import { Route as ApiPublicV1StatusRouteImport } from './routes/api/public/v1/status'
import { Route as ApiPublicV2DownloadRouteImport } from './routes/api/public/v2/download'
import { Route as ApiPublicV2SearchRouteImport } from './routes/api/public/v2/search'
import { Route as ApiPublicV2StatusRouteImport } from './routes/api/public/v2/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTelegramRoute = AdminTelegramRouteImport.update({
  id: '/admin/telegram',
  path: '/admin/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadIdRoute = ApiDownloadIdRouteImport.update({
  id: '/api/download/$id',
  path: '/api/download/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGuideYoutubeDotpyRoute =
  ApiPublicGuideYoutubeDotpyRouteImport.update({
    id: '/api/public/guide/youtube.py',
    path: '/api/public/guide/youtube.py',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramSetupRoute = ApiPublicTelegramSetupRouteImport.update({
  id: '/api/public/telegram/setup',
  path: '/api/public/telegram/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1DownloadRoute = ApiPublicV1DownloadRouteImport.update({
  id: '/api/public/v1/download',
  path: '/api/public/v1/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SearchRoute = ApiPublicV1SearchRouteImport.update({
  id: '/api/public/v1/search',
  path: '/api/public/v1/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1StatusRoute = ApiPublicV1StatusRouteImport.update({
  id: '/api/public/v1/status',
  path: '/api/public/v1/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV2DownloadRoute = ApiPublicV2DownloadRouteImport.update({
  id: '/api/public/v2/download',
  path: '/api/public/v2/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV2SearchRoute = ApiPublicV2SearchRouteImport.update({
  id: '/api/public/v2/search',
  path: '/api/public/v2/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV2StatusRoute = ApiPublicV2StatusRouteImport.update({
  id: '/api/public/v2/status',
  path: '/api/public/v2/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/developers': typeof DevelopersRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/api/download/$id': typeof ApiDownloadIdRoute
  '/api/public/guide/youtube.py': typeof ApiPublicGuideYoutubeDotpyRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/download': typeof ApiPublicV1DownloadRoute
  '/api/public/v1/search': typeof ApiPublicV1SearchRoute
  '/api/public/v1/status': typeof ApiPublicV1StatusRoute
  '/api/public/v2/download': typeof ApiPublicV2DownloadRoute
  '/api/public/v2/search': typeof ApiPublicV2SearchRoute
  '/api/public/v2/status': typeof ApiPublicV2StatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/developers': typeof DevelopersRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/api/download/$id': typeof ApiDownloadIdRoute
  '/api/public/guide/youtube.py': typeof ApiPublicGuideYoutubeDotpyRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/download': typeof ApiPublicV1DownloadRoute
  '/api/public/v1/search': typeof ApiPublicV1SearchRoute
  '/api/public/v1/status': typeof ApiPublicV1StatusRoute
  '/api/public/v2/download': typeof ApiPublicV2DownloadRoute
  '/api/public/v2/search': typeof ApiPublicV2SearchRoute
  '/api/public/v2/status': typeof ApiPublicV2StatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/developers': typeof DevelopersRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/api/download/$id': typeof ApiDownloadIdRoute
  '/api/public/guide/youtube.py': typeof ApiPublicGuideYoutubeDotpyRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/download': typeof ApiPublicV1DownloadRoute
  '/api/public/v1/search': typeof ApiPublicV1SearchRoute
  '/api/public/v1/status': typeof ApiPublicV1StatusRoute
  '/api/public/v2/download': typeof ApiPublicV2DownloadRoute
  '/api/public/v2/search': typeof ApiPublicV2SearchRoute
  '/api/public/v2/status': typeof ApiPublicV2StatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/developers'
    | '/admin/telegram'
    | '/api/download/$id'
    | '/api/public/guide/youtube.py'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/download'
    | '/api/public/v1/search'
    | '/api/public/v1/status'
    | '/api/public/v2/download'
    | '/api/public/v2/search'
    | '/api/public/v2/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/developers'
    | '/admin/telegram'
    | '/api/download/$id'
    | '/api/public/guide/youtube.py'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/download'
    | '/api/public/v1/search'
    | '/api/public/v1/status'
    | '/api/public/v2/download'
    | '/api/public/v2/search'
    | '/api/public/v2/status'
  id:
    | '__root__'
    | '/'
    | '/developers'
    | '/admin/telegram'
    | '/api/download/$id'
    | '/api/public/guide/youtube.py'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/download'
    | '/api/public/v1/search'
    | '/api/public/v1/status'
    | '/api/public/v2/download'
    | '/api/public/v2/search'
    | '/api/public/v2/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevelopersRoute: typeof DevelopersRoute
  AdminTelegramRoute: typeof AdminTelegramRoute
  ApiDownloadIdRoute: typeof ApiDownloadIdRoute
  ApiPublicGuideYoutubeDotpyRoute: typeof ApiPublicGuideYoutubeDotpyRoute
  ApiPublicTelegramSetupRoute: typeof ApiPublicTelegramSetupRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicV1DownloadRoute: typeof ApiPublicV1DownloadRoute
  ApiPublicV1SearchRoute: typeof ApiPublicV1SearchRoute
  ApiPublicV1StatusRoute: typeof ApiPublicV1StatusRoute
  ApiPublicV2DownloadRoute: typeof ApiPublicV2DownloadRoute
  ApiPublicV2SearchRoute: typeof ApiPublicV2SearchRoute
  ApiPublicV2StatusRoute: typeof ApiPublicV2StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/telegram': {
      id: '/admin/telegram'
      path: '/admin/telegram'
      fullPath: '/admin/telegram'
      preLoaderRoute: typeof AdminTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/$id': {
      id: '/api/download/$id'
      path: '/api/download/$id'
      fullPath: '/api/download/$id'
      preLoaderRoute: typeof ApiDownloadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/guide/youtube.py': {
      id: '/api/public/guide/youtube.py'
      path: '/api/public/guide/youtube.py'
      fullPath: '/api/public/guide/youtube.py'
      preLoaderRoute: typeof ApiPublicGuideYoutubeDotpyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/setup': {
      id: '/api/public/telegram/setup'
      path: '/api/public/telegram/setup'
      fullPath: '/api/public/telegram/setup'
      preLoaderRoute: typeof ApiPublicTelegramSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/download': {
      id: '/api/public/v1/download'
      path: '/api/public/v1/download'
      fullPath: '/api/public/v1/download'
      preLoaderRoute: typeof ApiPublicV1DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/search': {
      id: '/api/public/v1/search'
      path: '/api/public/v1/search'
      fullPath: '/api/public/v1/search'
      preLoaderRoute: typeof ApiPublicV1SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/status': {
      id: '/api/public/v1/status'
      path: '/api/public/v1/status'
      fullPath: '/api/public/v1/status'
      preLoaderRoute: typeof ApiPublicV1StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v2/download': {
      id: '/api/public/v2/download'
      path: '/api/public/v2/download'
      fullPath: '/api/public/v2/download'
      preLoaderRoute: typeof ApiPublicV2DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v2/search': {
      id: '/api/public/v2/search'
      path: '/api/public/v2/search'
      fullPath: '/api/public/v2/search'
      preLoaderRoute: typeof ApiPublicV2SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v2/status': {
      id: '/api/public/v2/status'
      path: '/api/public/v2/status'
      fullPath: '/api/public/v2/status'
      preLoaderRoute: typeof ApiPublicV2StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevelopersRoute: DevelopersRoute,
  AdminTelegramRoute: AdminTelegramRoute,
  ApiDownloadIdRoute: ApiDownloadIdRoute,
  ApiPublicGuideYoutubeDotpyRoute: ApiPublicGuideYoutubeDotpyRoute,
  ApiPublicTelegramSetupRoute: ApiPublicTelegramSetupRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicV1DownloadRoute: ApiPublicV1DownloadRoute,
  ApiPublicV1SearchRoute: ApiPublicV1SearchRoute,
  ApiPublicV1StatusRoute: ApiPublicV1StatusRoute,
  ApiPublicV2DownloadRoute: ApiPublicV2DownloadRoute,
  ApiPublicV2SearchRoute: ApiPublicV2SearchRoute,
  ApiPublicV2StatusRoute: ApiPublicV2StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
